// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu169iQII3FWbDzZ_iEU0b5Oanx39kdMU',
    appId: '1:1046038874580:web:a509b519bc167b9f2d2e41',
    messagingSenderId: '1046038874580',
    projectId: 'biggestatheart',
    authDomain: 'biggestatheart.firebaseapp.com',
    storageBucket: 'biggestatheart.appspot.com',
    measurementId: 'G-RC33NKYVHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoPETKIZY2_JCF9YvaZBfI5qIW1AMKdy4',
    appId: '1:1046038874580:android:f068f34ef3aa637e2d2e41',
    messagingSenderId: '1046038874580',
    projectId: 'biggestatheart',
    storageBucket: 'biggestatheart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmczQMghUcoEP-WTXRbq-UDDZSx5Or0C4',
    appId: '1:1046038874580:ios:896ba6fd6dd239392d2e41',
    messagingSenderId: '1046038874580',
    projectId: 'biggestatheart',
    storageBucket: 'biggestatheart.appspot.com',
    iosBundleId: 'com.example.biggestatheart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmczQMghUcoEP-WTXRbq-UDDZSx5Or0C4',
    appId: '1:1046038874580:ios:896ba6fd6dd239392d2e41',
    messagingSenderId: '1046038874580',
    projectId: 'biggestatheart',
    storageBucket: 'biggestatheart.appspot.com',
    iosBundleId: 'com.example.biggestatheart',
  );
}
